
clase(perro, mamifero).
clase(gato, mamifero).
clase(caballo, mamifero).
clase(vaca, mamifero).
clase(oveja, mamifero).
clase(cerdo, mamifero).
clase(conejo, mamifero).
clase(elefante, mamifero).
clase(leon, mamifero).
clase(tigre, mamifero).
clase(raton, mamifero).
clase(oso, mamifero).
clase(mono, mamifero).
clase(delfin, mamifero).
clase(ballena, mamifero).
clase(murcielago, mamifero).
clase(canguro, mamifero).
clase(jirafa, mamifero).
clase(zorro, mamifero).
clase(lobo, mamifero).
clase(aguila, ave).
clase(paloma, ave).
clase(loro, ave).
clase(buho, ave).
clase(gallo, ave).
clase(gallina, ave).
clase(cisne, ave).
clase(flamenco, ave).
clase(cuervo, ave).
clase(pavo_real, ave).
clase(gaviota, ave).
clase(colibri, ave).
clase(pinguino, ave).
clase(avestruz, ave).
clase(canario, ave).
clase(halcon, ave).
clase(pato, ave).
clase(tucan, ave).
clase(urraca, ave).
clase(perdiz, ave).
clase(tortuga, reptil).
clase(serpiente, reptil).
clase(cocodrilo, reptil).
clase(lagartija, reptil).
clase(camaleon, reptil).
clase(dragon_de_komodo, reptil).
clase(iguana, reptil).
clase(gecko, reptil).
clase(boa_constrictor, reptil).
clase(piton, reptil).
clase(caiman, reptil).
clase(basilisco, reptil).
clase(vibora, reptil).
clase(escinco, reptil).
clase(tortuga_de_tierra, reptil).
clase(serpiente_coral, reptil).
clase(anaconda, reptil).
clase(serpiente_de_cascabel, reptil).
clase(lagarto_espinoso, reptil).
clase(lagarto_cornudo, reptil).

subclase(perro, domestico).
subclase(gato, domestico).
subclase(caballo, domestico).
subclase(vaca, domestico).
subclase(oveja, domestico).
subclase(cerdo, domestico).
subclase(conejo, domestico).
subclase(elefante, salvaje).
subclase(leon, salvaje).
subclase(tigre, salvaje).
subclase(raton, domestico).
subclase(oso, salvaje).
subclase(mono, salvaje).
subclase(delfin, marino).
subclase(ballena, marino).
subclase(murcielago, volador).
subclase(canguro, terrestre).
subclase(jirafa, terrestre).
subclase(zorro, salvaje).
subclase(lobo, salvaje).
subclase(aguila, volador).
subclase(paloma, volador).
subclase(loro, volador).
subclase(buho, volador).
subclase(gallo, terrestre).
subclase(gallina, terrestre).
subclase(cisne, volador).
subclase(flamenco, terrestre).
subclase(cuervo, volador).
subclase(pavo_real, terrestre).
subclase(gaviota, volador).
subclase(colibri, volador).
subclase(pinguino, terrestre).
subclase(avestruz, terrestre).
subclase(canario, volador).
subclase(halcon, volador).
subclase(pato, terrestre).
subclase(tucan, volador).
subclase(urraca, volador).
subclase(perdiz, terrestre).
subclase(tortuga, terrestre).
subclase(serpiente, terrestre).
subclase(cocodrilo, acuatico).
subclase(lagartija, terrestre).
subclase(camaleon, trepador).
subclase(dragon_de_komodo, terrestre).
subclase(iguana, trepador).
subclase(gecko, trepador).
subclase(boa_constrictor, terrestre).
subclase(piton, terrestre).
subclase(caiman, acuatico).
subclase(basilisco, terrestre).
subclase(vibora, terrestre).
subclase(escinco, terrestre).
subclase(tortuga_de_tierra, terrestre).
subclase(serpiente_coral, terrestre).
subclase(anaconda, acuatico).
subclase(serpiente_de_cascabel, terrestre).
subclase(lagarto_espinoso, terrestre).
subclase(lagarto_cornudo, terrestre).

caracteristica(perro, tiene_pelo).
caracteristica(perro, ladra).
caracteristica(gato, tiene_pelo).
caracteristica(gato, maulla).
caracteristica(caballo, tiene_crin).
caracteristica(caballo, relincha).
caracteristica(caballo, corre_rapido).
caracteristica(vaca, da_leche).
caracteristica(vaca, rumia).
caracteristica(vaca, tiene_cuernos).
caracteristica(oveja, tiene_lana).
caracteristica(oveja, es_mansa).
caracteristica(oveja, bala).
caracteristica(cerdo, gruñe).
caracteristica(cerdo, es_rosado).
caracteristica(cerdo, tiene_hocico).
caracteristica(conejo, tiene_orejas_largas).
caracteristica(conejo, salta).
caracteristica(conejo, come_zanahorias).
caracteristica(elefante, tiene_trompa).
caracteristica(elefante, es_grande).
caracteristica(elefante, tiene_colmillos).
caracteristica(leon, tiene_melena).
caracteristica(leon, ruge).
caracteristica(leon, es_carnivoro).
caracteristica(tigre, tiene_rayas).
caracteristica(tigre, es_felino).
caracteristica(tigre, es_carnivoro).
caracteristica(raton, es_pequeno).
caracteristica(raton, tiene_bigotes).
caracteristica(raton, es_escurridizo).
caracteristica(oso, es_grande).
caracteristica(oso, tiene_garras).
caracteristica(oso, duerme_invierno).
caracteristica(mono, tiene_cola).
caracteristica(mono, trepa_arboles).
caracteristica(mono, come_bananas).
caracteristica(delfin, es_inteligente).
caracteristica(delfin, nada_rapido).
caracteristica(delfin, vive_en_el_mar).
caracteristica(ballena, es_grande).
caracteristica(ballena, tiene_aletas).
caracteristica(ballena, vive_en_el_mar).
caracteristica(murcielago, vuela).
caracteristica(murcielago, es_nocturno).
caracteristica(murcielago, usa_ecolocalizacion).
caracteristica(canguro, tiene_bolsa).
caracteristica(canguro, salta).
caracteristica(canguro, es_australiano).
caracteristica(jirafa, tiene_cuello_largo).
caracteristica(jirafa, es_alta).
caracteristica(jirafa, come_hojas).
caracteristica(zorro, es_astuto).
caracteristica(zorro, tiene_colarojiza).
caracteristica(zorro, es_rapido).
caracteristica(lobo, aulla).
caracteristica(lobo, vive_en_bosque).
caracteristica(lobo, tiene_colmillos).
caracteristica(aguila, vuela_alto).
caracteristica(aguila, tiene_garras).
caracteristica(aguila, es_carnivora).
caracteristica(paloma, es_blanca).
caracteristica(paloma, vuela).
caracteristica(paloma, emite_arrullo).
caracteristica(loro, repite_sonidos).
caracteristica(loro, tiene_colores).
caracteristica(loro, es_domestico).
caracteristica(buho, es_nocturno).
caracteristica(buho, gira_cabeza).
caracteristica(buho, tiene_grandes_ojos).
caracteristica(gallo, canta_al_amanecer).
caracteristica(gallo, tiene_crestas).
caracteristica(gallo, es_domestico).
caracteristica(gallina, pone_huevos).
caracteristica(gallina, es_domestica).
caracteristica(gallina, cacarea).
caracteristica(cisne, nada).
caracteristica(cisne, tiene_cuello_largo).
caracteristica(cisne, es_blanco).
caracteristica(flamenco, es_rosado).
caracteristica(flamenco, se_para_en_una_pierna).
caracteristica(flamenco, vive_en_pantanos).
caracteristica(cuervo, es_negro).
caracteristica(cuervo, es_inteligente).
caracteristica(cuervo, grazna).
caracteristica(pavo_real, abre_su_cola).
caracteristica(pavo_real, tiene_colores).
caracteristica(pavo_real, es_decorativo).
caracteristica(gaviota, vive_cerca_del_mar).
caracteristica(gaviota, vuela).
caracteristica(gaviota, come_peces).
caracteristica(colibri, vuela_estatico).
caracteristica(colibri, bebe_nectar).
caracteristica(colibri, es_pequeno).
caracteristica(pinguino, no_vuela).
caracteristica(pinguino, vive_en_el_frio).
caracteristica(pinguino, nada_bien).
caracteristica(avestruz, es_grande).
caracteristica(avestruz, no_vuela).
caracteristica(avestruz, corre_rapido).
caracteristica(canario, canta_bonito).
caracteristica(canario, es_domestico).
caracteristica(canario, es_amarillo).
caracteristica(halcon, vuela_rapido).
caracteristica(halcon, caza_otros_animales).
caracteristica(halcon, tiene_pico_gancho).
caracteristica(pato, nada).
caracteristica(pato, grazna).
caracteristica(pato, tiene_pico_ancho).
caracteristica(tucan, tiene_pico_grande).
caracteristica(tucan, es_colorido).
caracteristica(tucan, vive_en_selva).
caracteristica(urraca, es_curiosa).
caracteristica(urraca, recolecta_objetos).
caracteristica(urraca, es_negra_y_blanca).
caracteristica(perdiz, vive_en_campo).
caracteristica(perdiz, camina_rapido).
caracteristica(perdiz, es_pequena).
caracteristica(tortuga, tiene_caparazon).
caracteristica(tortuga, es_lenta).
caracteristica(tortuga, vive_muchos_anos).
caracteristica(serpiente, no_tiene_patas).
caracteristica(serpiente, se_arrastra).
caracteristica(serpiente, es_venenosa).
caracteristica(cocodrilo, tiene_dientes_afiliados).
caracteristica(cocodrilo, vive_en_rio).
caracteristica(cocodrilo, es_carnivoro).
caracteristica(lagartija, es_pequena).
caracteristica(lagartija, toma_sol).
caracteristica(lagartija, tiene_cola).
caracteristica(camaleon, cambia_color).
caracteristica(camaleon, tiene_ojos_independientes).
caracteristica(camaleon, es_lento).
caracteristica(dragon_de_komodo, es_grande).
caracteristica(dragon_de_komodo, es_carnivoro).
caracteristica(dragon_de_komodo, es_peligroso).
caracteristica(iguana, come_plantas).
caracteristica(iguana, es_verde).
caracteristica(iguana, vive_en_arboles).
caracteristica(gecko, se_adhiere_paredes).
caracteristica(gecko, es_nocturno).
caracteristica(gecko, hace_sonidos).
caracteristica(boa_constrictor, mata_abrazo).
caracteristica(boa_constrictor, es_grande).
caracteristica(boa_constrictor, no_es_venenosa).
caracteristica(piton, es_grande).
caracteristica(piton, no_es_venenosa).
caracteristica(piton, vive_en_selva).
caracteristica(caiman, vive_en_pantano).
caracteristica(caiman, tiene_cola_larga).
caracteristica(caiman, es_carnivoro).
caracteristica(basilisco, corre_sobre_agua).
caracteristica(basilisco, es_verde).
caracteristica(basilisco, es_pequeno).
caracteristica(vibora, es_venenosa).
caracteristica(vibora, se_arrastra).
caracteristica(vibora, tiene_colmillos).
caracteristica(escinco, tiene_patas_cortas).
caracteristica(escinco, es_colorido).
caracteristica(escinco, se_entierra).
caracteristica(tortuga_de_tierra, vive_en_tierra).
caracteristica(tortuga_de_tierra, tiene_caparazon).
caracteristica(tortuga_de_tierra, es_lenta).
caracteristica(serpiente_coral, es_colorida).
caracteristica(serpiente_coral, es_venenosa).
caracteristica(serpiente_coral, se_arrastra).
caracteristica(anaconda, es_muy_grande).
caracteristica(anaconda, vive_en_agua).
caracteristica(anaconda, es_cazadora).
caracteristica(serpiente_de_cascabel, tiene_cascabel).
caracteristica(serpiente_de_cascabel, es_venenosa).
caracteristica(serpiente_de_cascabel, hace_ruido).
caracteristica(lagarto_espinoso, tiene_espinas).
caracteristica(lagarto_espinoso, es_desertico).
caracteristica(lagarto_espinoso, es_pequeno).
caracteristica(lagarto_cornudo, tiene_cuernos).
caracteristica(lagarto_cornudo, se_camufla).
caracteristica(perro, es_viviparo).
caracteristica(perro, amamanta).
caracteristica(gato, es_viviparo).
caracteristica(gato, amamanta).
caracteristica(caballo, es_viviparo).
caracteristica(caballo, amamanta).
caracteristica(vaca, es_viviparo).
caracteristica(vaca, amamanta).
caracteristica(oveja, es_viviparo).
caracteristica(oveja, amamanta).
caracteristica(cerdo, es_viviparo).
caracteristica(cerdo, amamanta).
caracteristica(conejo, es_viviparo).
caracteristica(conejo, amamanta).
caracteristica(elefante, es_viviparo).
caracteristica(elefante, amamanta).
caracteristica(leon, es_viviparo).
caracteristica(leon, amamanta).
caracteristica(tigre, es_viviparo).
caracteristica(tigre, amamanta).
caracteristica(raton, es_viviparo).
caracteristica(raton, amamanta).
caracteristica(oso, es_viviparo).
caracteristica(oso, amamanta).
caracteristica(mono, es_viviparo).
caracteristica(mono, amamanta).
caracteristica(delfin, es_viviparo).
caracteristica(delfin, amamanta).
caracteristica(ballena, es_viviparo).
caracteristica(ballena, amamanta).
caracteristica(murcielago, es_viviparo).
caracteristica(murcielago, amamanta).
caracteristica(canguro, es_viviparo).
caracteristica(canguro, amamanta).
caracteristica(jirafa, es_viviparo).
caracteristica(jirafa, amamanta).
caracteristica(zorro, es_viviparo).
caracteristica(zorro, amamanta).
caracteristica(lobo, es_viviparo).
caracteristica(lobo, amamanta).
caracteristica(aguila, tiene_pico).
caracteristica(aguila, tiene_plumas).
caracteristica(paloma, tiene_pico).
caracteristica(paloma, tiene_plumas).
caracteristica(loro, tiene_pico).
caracteristica(loro, tiene_plumas).
caracteristica(buho, tiene_pico).
caracteristica(buho, tiene_plumas).
caracteristica(gallo, tiene_pico).
caracteristica(gallo, tiene_plumas).
caracteristica(gallina, tiene_pico).
caracteristica(gallina, tiene_plumas).
caracteristica(cisne, tiene_pico).
caracteristica(cisne, tiene_plumas).
caracteristica(flamenco, tiene_pico).
caracteristica(flamenco, tiene_plumas).
caracteristica(cuervo, tiene_pico).
caracteristica(cuervo, tiene_plumas).
caracteristica(pavo_real, tiene_pico).
caracteristica(pavo_real, tiene_plumas).
caracteristica(gaviota, tiene_pico).
caracteristica(gaviota, tiene_plumas).
caracteristica(colibri, tiene_pico).
caracteristica(colibri, tiene_plumas).
caracteristica(pinguino, tiene_pico).
caracteristica(pinguino, tiene_plumas).
caracteristica(avestruz, tiene_pico).
caracteristica(avestruz, tiene_plumas).
caracteristica(canario, tiene_pico).
caracteristica(canario, tiene_plumas).
caracteristica(halcon, tiene_pico).
caracteristica(halcon, tiene_plumas).
caracteristica(pato, tiene_pico).
caracteristica(pato, tiene_plumas).
caracteristica(tucan, tiene_pico).
caracteristica(tucan, tiene_plumas).
caracteristica(urraca, tiene_pico).
caracteristica(urraca, tiene_plumas).
caracteristica(perdiz, tiene_pico).
caracteristica(perdiz, tiene_plumas).
caracteristica(tortuga, tiene_escamas).
caracteristica(tortuga, sangre_fria).
caracteristica(serpiente, tiene_escamas).
caracteristica(serpiente, sangre_fria).
caracteristica(cocodrilo, tiene_escamas).
caracteristica(cocodrilo, sangre_fria).
caracteristica(lagartija, tiene_escamas).
caracteristica(lagartija, sangre_fria).
caracteristica(camaleon, tiene_escamas).
caracteristica(camaleon, sangre_fria).
caracteristica(dragon_de_komodo, tiene_escamas).
caracteristica(dragon_de_komodo, sangre_fria).
caracteristica(iguana, tiene_escamas).
caracteristica(iguana, sangre_fria).
caracteristica(gecko, tiene_escamas).
caracteristica(gecko, sangre_fria).
caracteristica(boa_constrictor, tiene_escamas).
caracteristica(boa_constrictor, sangre_fria).
caracteristica(piton, tiene_escamas).
caracteristica(piton, sangre_fria).
caracteristica(caiman, tiene_escamas).
caracteristica(caiman, sangre_fria).
caracteristica(basilisco, tiene_escamas).
caracteristica(basilisco, sangre_fria).
caracteristica(vibora, tiene_escamas).
caracteristica(vibora, sangre_fria).
caracteristica(escinco, tiene_escamas).
caracteristica(escinco, sangre_fria).
caracteristica(tortuga_de_tierra, tiene_escamas).
caracteristica(tortuga_de_tierra, sangre_fria).
caracteristica(serpiente_coral, tiene_escamas).
caracteristica(serpiente_coral, sangre_fria).
caracteristica(anaconda, tiene_escamas).
caracteristica(anaconda, sangre_fria).
caracteristica(serpiente_de_cascabel, tiene_escamas).
caracteristica(serpiente_de_cascabel, sangre_fria).
caracteristica(lagarto_espinoso, tiene_escamas).
caracteristica(lagarto_espinoso, sangre_fria).
caracteristica(lagarto_cornudo, tiene_escamas).
caracteristica(lagarto_cornudo, sangre_fria).

% Características únicas añadidas automáticamente
caracteristica(perro, protege_el_hogar).
caracteristica(gato, se_afila_las_garras).
caracteristica(elefante, usa_su_trompa_para_comer).
caracteristica(oso, atrapa_peces_con_las_garras).
caracteristica(delfin, realiza_saltos_en_el_agua).
